name: Simple workflow with inputs and outputs
on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:
    inputs:
      name:
        type: string
        default: 'BASIC_USER'
        required: false
      email:
        type: string
        default: 'basicuser@basic.com'
        required: false
env:
  greeting_string: 'Hello user ${{ inputs.name }}. This message is defined in an environment variable, with your username provided by input parameters.'
  files_string: 'These are your files'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first_parallel_job:
    name: First parallel job
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout the workflow-practice repository
      - name: Print a greeting created from the combination of input and environment variables
        run: |
          echo "${{ env.greeting_string }}"
        shell: powershell
      - name: Gather a list of files and use it as an input for the next step
        run: |
          echo "blabla"
        shell: powershell
      - name: Calculate the total file size and use it for the third job
        run: |
          echo "blabla"
        shell: powershell
  second_parallel_job:
    name: Second parallel job
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout the workflow-practice repository
      - name: Print a greeting created from the combination of input and environment variables
        run: |
          echo "${{ env.greeting_string }}"
        shell: powershell
  third_sequential_job:
   name: Third sequential job
   runs-on: windows-latest
   needs: [first_parallel_job,second_parallel_job]
   steps:
     - uses: actions/checkout@v3
       name: Checkout the workflow-practice repository
     - name: Print the calculated size from the first job
       run: |
         echo "Hello ${{ inputs.user }}. This is the file size calculated in the first job: "
       shell: powershell
